name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: Swatinem/rust-cache@v2

    - name: Rustfmt
      run: cargo fmt -- --check
    - name: Clippy
      run: |
        cargo --version
        cargo clippy --version
        cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used
    - name: Run tests
      run: cargo test --verbose
